import type { TenantRegistry } from '../../ports/tenant-registry';
import type { TenantClientProvider } from '../../ports/tenant-client-provider';
const SUPPORT_SESSION_MARKER = 'admin_support';
export interface SupportSessionDeps { tenantRegistry: TenantRegistry; tenantClientProvider: TenantClientProvider; randomId?: () => string; }
export class SearchUsersAcrossTenantsUseCase { constructor(private deps: SupportSessionDeps) {} async execute(options: { query?: string; tenantId?: string; limit?: number }) { const searchTerm = options.query?.trim(); const limit = Math.min(Math.max(options.limit ?? 50, 1), 200); const tenants = options.tenantId ? [this.deps.tenantRegistry.resolveTenant(options.tenantId)].filter(Boolean) as any[] : this.deps.tenantRegistry.getAllTenants().filter(t => t.status === 'active'); const out: unknown[] = []; for (const tenant of tenants) { if (out.length >= limit || tenant.status !== 'active') continue; const client = this.deps.tenantClientProvider.getClient(tenant.id); const where: any = searchTerm ? { OR: [{ email: { contains: searchTerm, mode: 'insensitive' } }, { name: { contains: searchTerm, mode: 'insensitive' } }, { id: searchTerm }] } : {}; const users = await client.user.findMany({ where, take: Math.max(Math.min(limit - out.length, limit), 1), orderBy: { createdAt: 'desc' } }); users.forEach((user: any) => out.push({ tenantId: tenant.id, tenantName: tenant.name, tenantSlug: tenant.slug, user, sessionCount: 0, organizations: [] })); } return out; } }
export class RevokeUserSessionsUseCase { constructor(private deps: SupportSessionDeps) {} async execute(tenantId: string, userId: string) { const result = await this.deps.tenantClientProvider.getClient(tenantId).session.deleteMany({ where: { userId } }); return result.count; } }
export class CreateSupportSessionUseCase { constructor(private deps: SupportSessionDeps) {} async execute(tenantId: string, userId: string, minutes = 30) { const id = this.deps.randomId?.() ?? crypto.randomUUID(); const token = `support_${id}`; const session = await this.deps.tenantClientProvider.getClient(tenantId).session.create({ data: { id: this.deps.randomId?.() ?? crypto.randomUUID(), token, userId, expiresAt: new Date(Date.now() + Math.max(minutes, 1) * 60000), impersonatedBy: SUPPORT_SESSION_MARKER } }); return { token: session.token, expiresAt: session.expiresAt }; } }
export class ListActiveSupportSessionsUseCase { constructor(private deps: SupportSessionDeps) {} async execute() { return []; } }
export class RevokeSupportSessionUseCase { constructor(private deps: SupportSessionDeps) {} async execute(tenantId: string, sessionId: string) { const result = await this.deps.tenantClientProvider.getClient(tenantId).session.deleteMany({ where: { id: sessionId, impersonatedBy: SUPPORT_SESSION_MARKER } }); return result.count > 0; } }
export class PruneIdleConnectionsUseCase { constructor(private deps: { connectionPruner: { pruneIdleConnectionsNow(options?: { force?: boolean }): Promise<number> } }) {} async execute(force = false) { return { pruned: await this.deps.connectionPruner.pruneIdleConnectionsNow({ force }) }; } }
