import type { SecuritySettingsRepository } from '../../ports/security-settings-repository';
import type { AuditLogRepository } from '../../ports/audit-log-repository';
import type { CreateIpBlockInput, IpBlockEntry, SecuritySettings, UpdateSecuritySettingsInput } from '../../domain/security/security-settings';
import { TenantValidationError } from '../../errors/tenant-errors';

export interface SecurityDefaults { trustedOrigins: string[]; enableDevEndpoints: boolean; }
export interface SecurityUseCaseDeps { securityRepository: SecuritySettingsRepository; auditLogRepository: AuditLogRepository; defaults: SecurityDefaults; ipUtils: { isValidIpOrCidr(ip: string): boolean; isIpInBlocklist(ip: string, list: IpBlockEntry[]): { blocked: boolean; matchedEntry?: IpBlockEntry }; convertIpv4Mapped(ip: string): string; }; }

export function defaultSecuritySettings(defaults: SecurityDefaults): SecuritySettings { return { trustedOrigins: defaults.trustedOrigins, enableDevEndpoints: defaults.enableDevEndpoints, apiKeyRotationDays: null, adminIpAllowlist: [], enforceAdminMfa: false, readOnlyMode: false, ipBlocklist: [], rateLimitOverrides: {}, enableIpBlocking: true, enableRateLimitLogging: true, blockOnRateLimitExceeded: false, rateLimitBlockDurationMs: 3600000 }; }

export class GetSecuritySettingsUseCase { constructor(private deps: SecurityUseCaseDeps) {} async execute(): Promise<SecuritySettings> { await this.deps.securityRepository.ensureAdminSettingsTable(); return this.deps.securityRepository.getSecuritySettings().then(s => ({ ...defaultSecuritySettings(this.deps.defaults), ...(s ?? {}) })); } }
export class UpdateSecuritySettingsUseCase { constructor(private deps: SecurityUseCaseDeps) {} async execute(adminUserId: string, updates: UpdateSecuritySettingsInput): Promise<SecuritySettings> { const current = await new GetSecuritySettingsUseCase(this.deps).execute(); const settings = { ...current, ...updates, trustedOrigins: updates.trustedOrigins ?? current.trustedOrigins, adminIpAllowlist: updates.adminIpAllowlist ?? current.adminIpAllowlist, apiKeyRotationDays: updates.apiKeyRotationDays === undefined ? current.apiKeyRotationDays : updates.apiKeyRotationDays } as SecuritySettings; await this.deps.securityRepository.updateSecuritySettings(adminUserId, settings); return settings; } }
export class GetIpBlocklistUseCase { constructor(private deps: SecurityUseCaseDeps) {} async execute(): Promise<IpBlockEntry[]> { const settings = await new GetSecuritySettingsUseCase(this.deps).execute(); const now = new Date(); return settings.ipBlocklist.filter(e => !e.expiresAt || e.expiresAt >= now); } }
export class BlockIpUseCase { constructor(private deps: SecurityUseCaseDeps) {} async execute(adminUserId: string, input: CreateIpBlockInput): Promise<IpBlockEntry> { if (!this.deps.ipUtils.isValidIpOrCidr(input.ip)) throw new TenantValidationError(`Invalid IP address or CIDR: ${input.ip}`); const settings = await new GetSecuritySettingsUseCase(this.deps).execute(); const entry: IpBlockEntry = { ip: input.ip, reason: input.reason, blockedAt: new Date(), blockedBy: input.blockedBy, expiresAt: input.expiresInMs ? new Date(Date.now() + input.expiresInMs) : null, isCidr: input.ip.includes('/') }; const idx = settings.ipBlocklist.findIndex(e => e.ip === input.ip); if (idx >= 0) settings.ipBlocklist[idx] = entry; else settings.ipBlocklist.push(entry); await this.deps.securityRepository.updateSecuritySettings(adminUserId, settings); await this.deps.auditLogRepository.logAuditAction(adminUserId, 'block_ip', 'security', input.ip, { reason: input.reason, expiresInMs: input.expiresInMs }); return entry; } }
export class UnblockIpUseCase { constructor(private deps: SecurityUseCaseDeps) {} async execute(adminUserId: string, ip: string): Promise<boolean> { const settings = await new GetSecuritySettingsUseCase(this.deps).execute(); const before = settings.ipBlocklist.length; settings.ipBlocklist = settings.ipBlocklist.filter(e => e.ip !== ip); const removed = settings.ipBlocklist.length !== before; if (removed) { await this.deps.securityRepository.updateSecuritySettings(adminUserId, settings); await this.deps.auditLogRepository.logAuditAction(adminUserId, 'unblock_ip', 'security', ip, {}); } return removed; } }
export class CheckIpBlockedUseCase { constructor(private deps: SecurityUseCaseDeps) {} async execute(ip: string): Promise<{ blocked: boolean; entry?: IpBlockEntry }> { const settings = await new GetSecuritySettingsUseCase(this.deps).execute(); if (!settings.enableIpBlocking) return { blocked: false }; const result = this.deps.ipUtils.isIpInBlocklist(this.deps.ipUtils.convertIpv4Mapped(ip), settings.ipBlocklist); return { blocked: result.blocked, entry: result.matchedEntry }; } }
