import type { TenantRepository } from '../../ports/tenant-repository';
import type { TenantRegistry } from '../../ports/tenant-registry';
import type { TenantClientProvider } from '../../ports/tenant-client-provider';
import type { AuthCache } from '../../ports/auth-cache';

export interface MetricsDeps { tenantRepository: TenantRepository; tenantRegistry: TenantRegistry & { getStats?: () => unknown }; tenantClientProvider: TenantClientProvider; authCache: AuthCache; }
export class GetTenantMetricsUseCase { constructor(private deps: Pick<MetricsDeps, 'tenantClientProvider'>) {} async execute(tenantId: string) { const client = this.deps.tenantClientProvider.getClient(tenantId); const [userCount, sessionCount, organizationCount] = await Promise.all([client.user.count(), client.session.count({ where: { expiresAt: { gt: new Date() } } }), client.organization.count()]); return { userCount, sessionCount, organizationCount }; } }
export class GetSystemMetricsUseCase { constructor(private deps: MetricsDeps) {} async execute() { const tenants = await this.deps.tenantRepository.getTenantStatusSnapshot(); const active = tenants.filter(t => t.status === 'active'); const metrics = await Promise.all(active.map(t => new GetTenantMetricsUseCase(this.deps).execute(t.id).catch(() => ({ userCount: 0, sessionCount: 0, organizationCount: 0 })))); return { totalTenants: tenants.length, activeTenants: active.length, suspendedTenants: tenants.filter(t=>t.status==='suspended').length, provisioningTenants: tenants.filter(t=>t.status==='provisioning').length, failedTenants: tenants.filter(t=>t.status==='failed').length, totalUsers: metrics.reduce((a,m)=>a+m.userCount,0), activeSessions: metrics.reduce((a,m)=>a+m.sessionCount,0), connections: this.deps.tenantRegistry.getStats?.() }; } }
export class GetAdminOverviewUseCase { constructor(private deps: MetricsDeps) {} async execute() { return { generatedAt: new Date().toISOString(), metrics: await new GetSystemMetricsUseCase(this.deps).execute(), authCache: this.deps.authCache.getStats() }; } }
export class GetDashboardMetricsUseCase { constructor(private deps: { metricsStore: { getMetrics(): Promise<unknown> } }) {} execute() { return this.deps.metricsStore.getMetrics(); } }
export class GetTimeSeriesUseCase { constructor(private deps: { metricsStore: { getTimeSeriesData(): Promise<unknown> } }) {} execute() { return this.deps.metricsStore.getTimeSeriesData(); } }
